server:
  port: 6000
  tomcat:
    connection-timeout: 6000

-Dreactor:
  netty:
    pool:
      leasingStrategy: lifo

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: false
  cloud:
    gateway:
      httpclient:
        pool:
          max-idle-time: 1000ms
      routes:
        - id: payment
          uri: lb://basic-arch-payment-api
          predicates:
            - Path= /api/payment/**

        - id: serial
          uri: lb://basic-arch-serial-api
          predicates:
            - Path=/serial/**

        - id: admin
          uri: lb://basic-arch-admin-web
          predicates:
            - Path=/api/admin/**

#feign调用超时时间  60s
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
    rabbit:
      enabled: false
    mongo:
      enabled: false
    mail:
      enabled: false
